name: 'Eric & Laura Get Married'
favicon: null
layout_spectrum: 0.09144
typography_spectrum: 0.71839
title: 'Eric & Laura Get Married'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c050c'
    - '#604823'
    - '#fdfefe'
    - '#c48133'
    - '#fccf92'
  brandStrength: 0.75
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
