name: 'Eric & Laura Get Married'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83309
title: 'Eric & Laura Get Married'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070c08'
    - '#23a795'
    - '#c5d4d1'
    - '#4cf9db'
    - '#316c82'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
