name: 'Eric & Laura Get Married'
favicon: null
layout_spectrum: 0.4176
typography_spectrum: 0.71839
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060c08'
    - '#00b29e'
    - '#00fadd'
    - '#c5d6d3'
    - '#5c5342'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
