name: 'Eric & Laura Get Married'
favicon: null
layout_spectrum: 0.09144
typography_spectrum: 0.71839
title: 'Eric & Laura Get Married'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060503'
    - '#fbde3b'
    - '#a74a33'
    - '#dc8d7a'
    - '#e6c6be'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
